### ISSUE TITLE
Make force_torque_tools work with the PR2

### ISSUE THREAD

**Issue by sotte** [kth-ros-pkg/force_torque_tools#1]
I'm currently working on this. However, there are some problems:
- the FT sensor does not include the frame_id
- the grippers don't have an IMU but only an accelerometer

I'll update this issue as I go along. Once it works I'll create a pull request.

**Comment by diogoalmeida** [comment]
The calibration method requires knowledge of the sensor frame in order to compensate the measurements. If I recall correctly, we had to add the frame_id to the messages published by our PR2 FT sensors. I am also pretty sure the PR2 has an IMU. This does not need to be at the grippers, as we only use it to get the gravity vector.
